chore: minor FSM docs enhancements
TBD54566975/ftl pull request #2541
Opened 2024-08-29 15:59 UTC by stuartwdouglas

2024-08-29 23:26 UTC, alecthomas approved these changes

2024-08-30 04:33 UTC, matt2e requested changes
Looks good otherwise 👍

2024-08-30 04:33 UTC, matt2e commented on docs/content/docs/reference/fsm.md
> +err = payment.Send(ctx, invoiceID, Recipt {Amount: 110})
```suggestion
err = payment.Send(ctx, invoiceID, Receipt {Amount: 110})
```

2024-08-30 04:33 UTC, matt2e commented on docs/content/docs/reference/fsm.md
> +err = payment.Send(ctx, invoiceID, Recipt {Amount: 20})
```suggestion
err = payment.Send(ctx, invoiceID, Receipt {Amount: 20})
```

2024-09-01 23:58 UTC, matt2e approved these changes

2024-09-02 07:02 UTC, merged